<?php

namespace Mynd\Proxy;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class MyndEntityUsrProxy extends \Mynd\Entity\Usr implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    private function _load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister);
            unset($this->_identifier);
        }
    }

    
    public function getId()
    {
        $this->_load();
        return parent::getId();
    }

    public function setLogin($login)
    {
        $this->_load();
        return parent::setLogin($login);
    }

    public function getLogin()
    {
        $this->_load();
        return parent::getLogin();
    }

    public function setPssw($pssw)
    {
        $this->_load();
        return parent::setPssw($pssw);
    }

    public function getPssw()
    {
        $this->_load();
        return parent::getPssw();
    }

    public function checkPassword(&$password)
    {
        $this->_load();
        return parent::checkPassword($password);
    }

    public function hashPassword($password)
    {
        $this->_load();
        return parent::hashPassword($password);
    }


    public function __sleep()
    {
        if (!$this->__isInitialized__) {
            throw new \RuntimeException("Not fully loaded proxy can not be serialized.");
        }
        return array('id', 'login', 'pssw');
    }
}