CREATE TABLE usr
(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	login VARCHAR(255) NOT NULL,
	pssw VARCHAR(32) NOT NULL
);

CREATE TABLE item
(
	id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	path TEXT NOT NULL,
	name TEXT NOT NULL,
	status INT NOT NULL
);